import { Complaint } from './types';

export const mockComplaints: Complaint[] = [
  {
    id: 'CMP-2026-001',
    dateTime: '2026-02-14T09:30:00',
    store: 'Retail Store – Mumbai',
    department: 'Sales Floor',
    category: 'Electrical',
    description: 'Main lighting not working in section B. Entire area is dark, affecting customer experience.',
    priority: 'High',
    status: 'In Progress',
    reportedBy: 'John D.',
    assignedTo: 'ABC Electrical Services',
    contactNumber: '+91 98765 43210',
    expectedResolution: '2026-02-15',
  },
  {
    id: 'CMP-2026-002',
    dateTime: '2026-02-13T14:15:00',
    store: 'Retail Store – Delhi',
    department: 'IT',
    category: 'IT Support',
    description: 'POS terminal #3 not booting up. Shows blank screen after power on.',
    priority: 'Critical',
    status: 'Assigned',
    reportedBy: 'Priya M.',
    assignedTo: 'TechFix Solutions',
    contactNumber: '+91 87654 32109',
    expectedResolution: '2026-02-14',
  },
  {
    id: 'CMP-2026-003',
    dateTime: '2026-02-13T11:00:00',
    store: 'Retail Store – Bangalore',
    department: 'Warehouse',
    category: 'Plumbing',
    description: 'Water leakage from ceiling pipe near storage rack #12.',
    priority: 'High',
    status: 'Open',
    reportedBy: 'Rajesh K.',
    contactNumber: '+91 76543 21098',
    expectedResolution: '2026-02-16',
  },
  {
    id: 'CMP-2026-004',
    dateTime: '2026-02-12T16:45:00',
    store: 'Retail Store – Chennai',
    department: 'Customer Service',
    category: 'HVAC',
    description: 'AC not cooling in customer service area. Temperature is above 30°C.',
    priority: 'Medium',
    status: 'Closed (Pending)',
    reportedBy: 'Anita S.',
    assignedTo: 'CoolAir Services',
    contactNumber: '+91 65432 10987',
    expectedResolution: '2026-02-13',
    actualResolution: '2026-02-13',
    remarks: 'Compressor replaced. Testing pending.',
  },
  {
    id: 'CMP-2026-005',
    dateTime: '2026-02-12T10:00:00',
    store: 'Warehouse – Pune',
    department: 'Facilities',
    category: 'Flooring',
    description: 'Broken floor tiles near entrance causing trip hazard.',
    priority: 'High',
    status: 'Closed',
    reportedBy: 'Vikram P.',
    assignedTo: 'FloorMasters',
    contactNumber: '+91 54321 09876',
    expectedResolution: '2026-02-13',
    actualResolution: '2026-02-12',
    closureApproval: true,
    remarks: 'Tiles replaced. Area inspected and cleared.',
  },
  {
    id: 'CMP-2026-006',
    dateTime: '2026-02-11T08:30:00',
    store: 'Head Office – Mumbai',
    department: 'Admin',
    category: 'Network',
    description: 'WiFi connectivity issues on 3rd floor. Intermittent drops every 10 minutes.',
    priority: 'Medium',
    status: 'In Progress',
    reportedBy: 'Suman R.',
    assignedTo: 'NetConnect IT',
    contactNumber: '+91 43210 98765',
    expectedResolution: '2026-02-14',
  },
  {
    id: 'CMP-2026-007',
    dateTime: '2026-02-11T13:20:00',
    store: 'Retail Store – Hyderabad',
    department: 'Sales Floor',
    category: 'Painting',
    description: 'Wall paint peeling off near display window. Looks unprofessional.',
    priority: 'Low',
    status: 'On Hold',
    reportedBy: 'Meera L.',
    contactNumber: '+91 32109 87654',
    remarks: 'Waiting for paint supply delivery.',
  },
  {
    id: 'CMP-2026-008',
    dateTime: '2026-02-10T15:00:00',
    store: 'Retail Store – Kolkata',
    department: 'Security',
    category: 'Carpentry',
    description: 'Main entrance door hinge broken. Door not closing properly.',
    priority: 'High',
    status: 'Assigned',
    reportedBy: 'Arun G.',
    assignedTo: 'WoodWorks Co.',
    contactNumber: '+91 21098 76543',
    expectedResolution: '2026-02-12',
  },
  {
    id: 'CMP-2026-009',
    dateTime: '2026-02-10T09:15:00',
    store: 'Retail Store – Mumbai',
    department: 'Back Office',
    category: 'Interior Works',
    description: 'Partition wall needed for new meeting room setup.',
    priority: 'Low',
    status: 'Open',
    reportedBy: 'Deepa N.',
    contactNumber: '+91 10987 65432',
  },
  {
    id: 'CMP-2026-010',
    dateTime: '2026-02-09T11:45:00',
    store: 'Retail Store – Delhi',
    department: 'Facilities',
    category: 'Building Construction',
    description: 'Crack in exterior wall near loading dock. Needs structural assessment.',
    priority: 'Critical',
    status: 'In Progress',
    reportedBy: 'Karan T.',
    assignedTo: 'BuildRight Constructions',
    contactNumber: '+91 09876 54321',
    expectedResolution: '2026-02-20',
    remarks: 'Structural engineer visit scheduled for Feb 15.',
  },
];
